name: Run security with SonarQube
on: push

jobs:
  sonarqube:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  owasp_zap:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: action/checkout@v4

      - name: Build docker container
        run: docker build -t vuln-webapp:bad .

      - name: Run docker container
        run: docker run --rm -p 9000:9000 --name vuln-app vuln-webapp:bad

      - name: Wait for app to be ready
        run: |
          echo "Waiting for app to start..."
          sleep 10
          curl -f http://localhost:9000 || (echo "App did not start" && exit 1)

      - name: ZAP Scan
        uses: zaproxy/action-full-scan@v0.12.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          docker_name: 'ghcr.io/zaproxy/zaproxy:stable'
          target: 'http://localhost:9000'
          cmd_options: '-a'